### ISSUE TITLE
Additional instance to support

### ISSUE THREAD

**Issue by blackluster117** [helloyanis/Lemmy-Language-Memorizer#1]
Could you please add support for possumpat.io? I would really appreciate it. Thank you for taking the time to make this add-on!

**Comment by helloyanis** [comment]
I have just updated it. The mozilla add-on team may take a while to verify it, but if you want to download it early, you can get the binaries from the releases page. Tell me if that works because I don't have an account on this instance! If it does work, please close the issue.

**Comment by blackluster117** [comment]
To clarify the behaviour, it should remember my language choice for initial comments on a post and replies to comments in a thread, correct? It doesn't seem to do so. Is it only when creating a post?

**Comment by blackluster117** [comment]
It seems to be working now. Closing the issue. Thank you for the change!
